### ISSUE TITLE
望潮登录成功后报错

### ISSUE THREAD

**Issue by dizzying** [Rookie-wb-WH/ql_scripts#3]
登录成功，然后提示IP黑了、无Session。
在手机上打开app进入一次阅读有礼，然后再执行脚本就可以正常完成任务了。
之后可以正常跑两天，然后又重复此错误。

报错信息如下：
```
✅XXXX,登陆成功!
⛔️阅读登陆,可能是IP黑了，稍后再尝试吧...
⛔️阅读文章,无Session，请重新登录...
```

**Comment by Rookie-wb-WH** [comment]
这是5天前更新后的嘛?
最新的日志应该是这样的
![QQ截图20240829003304](https://github.com/user-attachments/assets/865c9d62-c5eb-4eaf-9cb8-161e6cf76464)
